using System.ComponentModel;

namespace CoreApp.Infrastructure.Enums
{
    public enum FeatherIcons
    {
        [Description("ft-activity")]
        e900,
        [Description("ft-airplay")]
        e901,
        [Description("ft-alert-circle")]
        e902,
        [Description("ft-alert-octagon")]
        e903,
        [Description("ft-alert-triangle")]
        e904,
        [Description("ft-align-center")]
        e905,
        [Description("ft-align-justify")]
        e906,
        [Description("ft-align-left")]
        e907,
        [Description("ft-align-right")]
        e908,
        [Description("ft-anchor")]
        e909,
        [Description("ft-aperture")]
        e90a,
        [Description("ft-arrow-down-left")]
        e90b,
        [Description("ft-arrow-down-right")]
        e90c,
        [Description("ft-arrow-down")]
        e90d,
        [Description("ft-arrow-left")]
        e90e,
        [Description("ft-arrow-right")]
        e90f,
        [Description("ft-arrow-up-left")]
        e910,
        [Description("ft-arrow-up-right")]
        e911,
        [Description("ft-arrow-up")]
        e912,
        [Description("ft-at-sign")]
        e913,
        [Description("ft-award")]
        e914,
        [Description("ft-bar-chart-2")]
        e915,
        [Description("ft-bar-chart")]
        e916,
        [Description("ft-battery-charging")]
        e917,
        [Description("ft-battery")]
        e918,
        [Description("ft-bell-off")]
        e919,
        [Description("ft-bell")]
        e91a,
        [Description("ft-bluetooth")]
        e91b,
        [Description("ft-bold")]
        e9ea,
        [Description("ft-book")]
        e91c,
        [Description("ft-bookmark")]
        e91d,
        [Description("ft-box")]
        e91e,
        [Description("ft-briefcase")]
        e91f,
        [Description("ft-calendar")]
        e920,
        [Description("ft-camera-off")]
        e921,
        [Description("ft-camera")]
        e922,
        [Description("ft-cast")]
        e923,
        [Description("ft-check-circle")]
        e924,
        [Description("ft-check-square")]
        e925,
        [Description("ft-check")]
        e926,
        [Description("ft-chevron-down")]
        e927,
        [Description("ft-chevron-left")]
        e928,
        [Description("ft-chevron-right")]
        e929,
        [Description("ft-chevron-up")]
        e92a,
        [Description("ft-chevrons-down")]
        e92b,
        [Description("ft-chevrons-left")]
        e92c,
        [Description("ft-chevrons-right")]
        e92d,
        [Description("ft-chevrons-up")]
        e92e,
        [Description("ft-chrome")]
        e92f,
        [Description("ft-circle")]
        e930,
        [Description("ft-clipboard")]
        e931,
        [Description("ft-clock")]
        e932,
        [Description("ft-cloud-drizzle")]
        e933,
        [Description("ft-cloud-lightning")]
        e934,
        [Description("ft-cloud-off")]
        e935,
        [Description("ft-cloud-rain")]
        e936,
        [Description("ft-cloud-snow")]
        e937,
        [Description("ft-cloud")]
        e938,
        [Description("ft-codepen")]
        e939,
        [Description("ft-command")]
        e93a,
        [Description("ft-compass")]
        e93b,
        [Description("ft-copy")]
        e93c,
        [Description("ft-corner-down-left")]
        e93d,
        [Description("ft-corner-down-right")]
        e93e,
        [Description("ft-corner-left-down")]
        e93f,
        [Description("ft-corner-left-up")]
        e940,
        [Description("ft-corner-right-down")]
        e941,
        [Description("ft-corner-right-up")]
        e942,
        [Description("ft-corner-up-left")]
        e943,
        [Description("ft-corner-up-right")]
        e944,
        [Description("ft-cpu")]
        e945,
        [Description("ft-credit-card")]
        e946,
        [Description("ft-crop")]
        e9eb,
        [Description("ft-crosshair")]
        e947,
        [Description("ft-delete")]
        e948,
        [Description("ft-disc")]
        e949,
        [Description("ft-download-cloud")]
        e94a,
        [Description("ft-download")]
        e94b,
        [Description("ft-droplet")]
        e94c,
        [Description("ft-edit-2")]
        e94d,
        [Description("ft-edit-3")]
        e94e,
        [Description("ft-edit")]
        e94f,
        [Description("ft-external-link")]
        e950,
        [Description("ft-eye-off")]
        e951,
        [Description("ft-eye")]
        e952,
        [Description("ft-facebook")]
        e953,
        [Description("ft-fast-forward")]
        e954,
        [Description("ft-feather")]
        e955,
        [Description("ft-file-minus")]
        e956,
        [Description("ft-file-plus")]
        e957,
        [Description("ft-file-text")]
        e958,
        [Description("ft-file")]
        e959,
        [Description("ft-film")]
        e95a,
        [Description("ft-filter")]
        e95b,
        [Description("ft-flag")]
        e95c,
        [Description("ft-folder")]
        e95d,
        [Description("ft-github")]
        e95e,
        [Description("ft-gitlab")]
        e95f,
        [Description("ft-globe")]
        e960,
        [Description("ft-grid")]
        e961,
        [Description("ft-hash")]
        e962,
        [Description("ft-headphones")]
        e963,
        [Description("ft-heart")]
        e964,
        [Description("ft-help-circle")]
        e9ec,
        [Description("ft-home")]
        e965,
        [Description("ft-image")]
        e966,
        [Description("ft-inbox")]
        e967,
        [Description("ft-info")]
        e968,
        [Description("ft-instagram")]
        e969,
        [Description("ft-italic")]
        e9ed,
        [Description("ft-layers")]
        e96a,
        [Description("ft-layout")]
        e96b,
        [Description("ft-life-buoy")]
        e96c,
        [Description("ft-link-2")]
        e96d,
        [Description("ft-link")]
        e96e,
        [Description("ft-list")]
        e96f,
        [Description("ft-loader")]
        e970,
        [Description("ft-lock")]
        e971,
        [Description("ft-log-in")]
        e972,
        [Description("ft-log-out")]
        e973,
        [Description("ft-mail")]
        e974,
        [Description("ft-map-pin")]
        e975,
        [Description("ft-map")]
        e976,
        [Description("ft-maximize-2")]
        e977,
        [Description("ft-maximize")]
        e978,
        [Description("ft-menu")]
        e979,
        [Description("ft-message-circle")]
        e97a,
        [Description("ft-message-square")]
        e97b,
        [Description("ft-mic-off")]
        e97c,
        [Description("ft-mic")]
        e97d,
        [Description("ft-minimize-2")]
        e97e,
        [Description("ft-minimize")]
        e97f,
        [Description("ft-minus-circle")]
        e980,
        [Description("ft-minus-square")]
        e981,
        [Description("ft-minus")]
        e982,
        [Description("ft-monitor")]
        e983,
        [Description("ft-moon")]
        e984,
        [Description("ft-more-horizontal")]
        e985,
        [Description("ft-more-vertical")]
        e986,
        [Description("ft-move")]
        e987,
        [Description("ft-music")]
        e988,
        [Description("ft-navigation-2")]
        e989,
        [Description("ft-navigation")]
        e98a,
        [Description("ft-octagon")]
        e98b,
        [Description("ft-package")]
        e98c,
        [Description("ft-paperclip")]
        e98d,
        [Description("ft-pause-circle")]
        e98e,
        [Description("ft-pause")]
        e98f,
        [Description("ft-percent")]
        e990,
        [Description("ft-phone-call")]
        e991,
        [Description("ft-phone-forwarded")]
        e992,
        [Description("ft-phone-incoming")]
        e993,
        [Description("ft-phone-missed")]
        e994,
        [Description("ft-phone-off")]
        e995,
        [Description("ft-phone-outgoing")]
        e996,
        [Description("ft-phone")]
        e997,
        [Description("ft-pie-chart")]
        e998,
        [Description("ft-play-circle")]
        e999,
        [Description("ft-play")]
        e99a,
        [Description("ft-plus-circle")]
        e99b,
        [Description("ft-plus-square")]
        e99c,
        [Description("ft-plus")]
        e99d,
        [Description("ft-pocket")]
        e99e,
        [Description("ft-power")]
        e99f,
        [Description("ft-printer")]
        e9a0,
        [Description("ft-radio")]
        e9a1,
        [Description("ft-refresh-ccw")]
        e9a2,
        [Description("ft-refresh-cw")]
        e9a3,
        [Description("ft-repeat")]
        e9a4,
        [Description("ft-rewind")]
        e9a5,
        [Description("ft-rotate-ccw")]
        e9a6,
        [Description("ft-rotate-cw")]
        e9a7,
        [Description("ft-save")]
        e9a8,
        [Description("ft-scissors")]
        e9a9,
        [Description("ft-search")]
        e9aa,
        [Description("ft-server")]
        e9ab,
        [Description("ft-settings")]
        e9ac,
        [Description("ft-share-2")]
        e9ad,
        [Description("ft-share")]
        e9ae,
        [Description("ft-shield")]
        e9af,
        [Description("ft-shopping-cart")]
        e9ee,
        [Description("ft-shuffle")]
        e9b0,
        [Description("ft-sidebar")]
        e9b1,
        [Description("ft-skip-back")]
        e9b2,
        [Description("ft-skip-forward")]
        e9b3,
        [Description("ft-slack")]
        e9b4,
        [Description("ft-slash")]
        e9b5,
        [Description("ft-sliders")]
        e9b6,
        [Description("ft-smartphone")]
        e9b7,
        [Description("ft-speaker")]
        e9b8,
        [Description("ft-square")]
        e9b9,
        [Description("ft-star")]
        e9ba,
        [Description("ft-stop-circle")]
        e9bb,
        [Description("ft-sun")]
        e9bc,
        [Description("ft-sunrise")]
        e9bd,
        [Description("ft-sunset")]
        e9be,
        [Description("ft-tablet")]
        e9bf,
        [Description("ft-tag")]
        e9c0,
        [Description("ft-target")]
        e9c1,
        [Description("ft-thermometer")]
        e9c2,
        [Description("ft-thumbs-down")]
        e9c3,
        [Description("ft-thumbs-up")]
        e9c4,
        [Description("ft-toggle-left")]
        e9c5,
        [Description("ft-toggle-right")]
        e9c6,
        [Description("ft-trash-2")]
        e9c7,
        [Description("ft-trash")]
        e9c8,
        [Description("ft-trending-down")]
        e9c9,
        [Description("ft-trending-up")]
        e9ca,
        [Description("ft-triangle")]
        e9cb,
        [Description("ft-tv")]
        e9cc,
        [Description("ft-twitter")]
        e9cd,
        [Description("ft-type")]
        e9ce,
        [Description("ft-umbrella")]
        e9cf,
        [Description("ft-underline")]
        e9ef,
        [Description("ft-unlock")]
        e9d0,
        [Description("ft-upload-cloud")]
        e9d1,
        [Description("ft-upload")]
        e9d2,
        [Description("ft-user-check")]
        e9d3,
        [Description("ft-user-minus")]
        e9d4,
        [Description("ft-user-plus")]
        e9d5,
        [Description("ft-user-x")]
        e9d6,
        [Description("ft-user")]
        e9d7,
        [Description("ft-users")]
        e9d8,
        [Description("ft-video-off")]
        e9d9,
        [Description("ft-video")]
        e9da,
        [Description("ft-voicemail")]
        e9db,
        [Description("ft-volume-1")]
        e9dc,
        [Description("ft-volume-2")]
        e9dd,
        [Description("ft-volume-x")]
        e9de,
        [Description("ft-volume")]
        e9df,
        [Description("ft-watch")]
        e9e0,
        [Description("ft-wifi-off")]
        e9e1,
        [Description("ft-wifi")]
        e9e2,
        [Description("ft-wind")]
        e9e3,
        [Description("ft-x-circle")]
        e9e4,
        [Description("ft-x-square")]
        e9e5,
        [Description("ft-x")]
        e9e6,
        [Description("ft-zap")]
        e9e7,
        [Description("ft-zoom-in")]
        e9e8,
        [Description("ft-zoom-out")]
        e9e9
    }
}
